name: Generate Release Notes

on:
  push:
    tags:
      - 'v*'

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
      - name: Generate release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          generate-release-notes --repo ${{ github.repository }} --from-tag ${{ github.event.release.previous_tag_name }} --to-tag ${{ github.ref_name }} --llm-provider anthropic
      - name: Commit release notes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add release_notes.txt
          git commit -m "Add release notes for ${{ github.ref_name }}"
          git push
